var bill = { title: 'Savings (Government Contributions) Bill: Report Stage New Clause 2',
    number: 104,
    date: '2016-12-12T18:34:00',
    ayesCount: 230,
    noesCount: 277,
    abstainCount: 143,
    ayesByParty:
     { Labour: 155,
       Conservative: 0,
       'Scottish National Party': 35,
       'Liberal Democrat': 6,
       'Sinn Féin': 0,
       'Plaid Cymru': 1,
       'Democratic Unionist Party': 6,
       'Green Party': 0,
       Independent: 4 },
    noesByParty:
     { Labour: 0,
       Conservative: 275,
       'Scottish National Party': 0,
       'Liberal Democrat': 0,
       'Sinn Féin': 0,
       'Plaid Cymru': 0,
       'Democratic Unionist Party': 0,
       'Green Party': 0,
       Independent: 2 },
    glossText: 'To pass the bill',
    glossTitle: 'Main vote',
    isMainVote: true }